.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2018 Wookey <wookey@debian.org>,
.\"
.TH HORIZON-IMP 1 "2018.03.31"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
horizon-imp \- horizon EDA interactive manipulator

.SH SYNOPSIS
.RI horizon-imp
\-y \fI<symbol file>\fP | 
\-c \fI<schematic file> <block file>\fP |
\-a \fI<padstack file>\fP |
\-k \fI<package file>\fP |
\-b \fI<board file> <block file> <via directory>\fP
.br

.SH DESCRIPTION
This manual page documents the
.B horizon-imp
command.
.PP
.B horizon-imp is the 'interactive manipulator' and can be run in one of 5 modes, each operating on a different type of item: symbol, schematic, padstack, package or board.

.SH OPTIONS
Details of options are included below.
.TP
.B \-y \fI<symbol file>\fP
Run in Symbol mode: 
.TP
.B \-c \fI<schematic file> <block file>\fP
Run in Schematic mode
.TP
.B \-a \fI<padstack file>\fP
Run in Padstack mode
.TP
.B \-k \fI<package file>\fP
Run in Package mode
.TP
.B \-b \fI<board file <block file> <via directory>\fP
Run in Board mode

.SH USAGE
There is normally little reason to run this command directly.
Normally horizon-prj-mgr and horizon-pool-mgr are used. But
it remains useful for debugging.

.SH ENVIRONMENT
This command requires the environment variable HORIZON_POOL to point to the pool's directory (the one with the pool.json and pool.db in it)
