name: Build Debian packages

on:
  push:
    branches: [ '*' ]
    tags: [ '*' ]
  pull_request:
    branches: [ master ]

env:
  HORIZON_VERSION: 1.3.0
  HORIZON_PKG_VERSION: 1
  DEBIAN_FRONTEND: noninteractive
  LANG: en_US.UTF-8

jobs:
  build:
    strategy:
      matrix:
        os: 
          - distro: debian
            release: buster
          - distro: ubuntu
            release: bionic
          - distro: ubuntu
            release: focal
          - distro: ubuntu
            release: groovy
    runs-on: ubuntu-latest
    container: ${{ matrix.os.distro }}:${{ matrix.os.release }}
    steps:
    - name: check if master branch
      if: ${{ github.ref == 'refs/heads/master' }}
      run: echo "Building tag ${{ github.ref }}"
    - name: update apt cache
      run: apt-get update
    - name: install dependencies
      run: apt-get install -y git build-essential libsqlite3-dev util-linux librsvg2-dev libcairomm-1.0-dev libepoxy-dev libgtkmm-3.0-dev uuid-dev libboost-dev  libzmq5 libzmq3-dev libglm-dev libgit2-dev libcurl4-gnutls-dev liboce-ocaf-dev libpodofo-dev python3 libzip-dev git libdxflib-dev
    - name: install build utils
      run: apt-get install -y devscripts build-essential lintian wget debhelper curl
    - name: fix locale on bionic
      if: ${{ matrix.os.release == 'bionic' }}
      run: |
        apt-get install locales
        locale-gen ${{ env.LANG }}

    - uses: actions/checkout@v2
    - name: download tarball
      run: wget https://github.com/horizon-eda/horizon/archive/v${HORIZON_VERSION}.tar.gz -O horizon-eda_${HORIZON_VERSION}.orig.tar.gz

    - name: unpack tarball and add debian directory
      run: |
        tar xzf horizon-eda_${HORIZON_VERSION}.orig.tar.gz
        mv horizon-${HORIZON_VERSION} horizon-eda-${HORIZON_VERSION}
        cp -r debian horizon-eda-${HORIZON_VERSION}

    - name: run debuild
      run: debuild -uc -us
      working-directory: horizon-eda-${{ env. HORIZON_VERSION }}

    - name: list files
      run: ls
    - name: upload debian packages
      uses: actions/upload-artifact@v2-preview
      with:
        name: packages
        path: ./*.*deb
    - name: upload debian source files
      uses: actions/upload-artifact@v2-preview
      with:
        name: source-packages
        path: |
          *.dsc
          *.debian.tar.*
          *.orig.tar.*
    - name: Push to bintray
      if: ${{ github.ref == 'refs/heads/master' }}
      run: |
        curl -T horizon-eda_${{ env.HORIZON_VERSION }}-${{ env.HORIZON_PKG_VERSION }}_amd64.deb -ucarrotindustries:${{ secrets.BINTRAY_API_KEY }}  https://api.bintray.com/content/horizon-eda/horizon-eda-${{ matrix.os.release }}/horizon-eda/${{ env.HORIZON_VERSION }}-${{ env.HORIZON_PKG_VERSION }}/pool/main/h/horizon-eda_${{ env.HORIZON_VERSION }}-${{ env.HORIZON_PKG_VERSION }}_amd64.deb -H 'X-Bintray-Debian-Distribution: horizon-eda-${{ matrix.os.release }}' -H 'X-Bintray-Debian-Component: main' -H 'X-Bintray-Debian-Architecture: amd64' -H 'X-Bintray-Publish: 1'
        curl -T horizon-eda-dbgsym_${{ env.HORIZON_VERSION }}-${{ env.HORIZON_PKG_VERSION }}_amd64.* -ucarrotindustries:${{ secrets.BINTRAY_API_KEY }}  https://api.bintray.com/content/horizon-eda/horizon-eda-${{ matrix.os.release }}/horizon-eda/${{ env.HORIZON_VERSION }}-${{ env.HORIZON_PKG_VERSION }}/pool/main/h/horizon-eda-dbgsym_${{ env.HORIZON_VERSION }}-${{ env.HORIZON_PKG_VERSION }}_amd64.deb -H 'X-Bintray-Debian-Distribution: horizon-eda-${{ matrix.os.release }}' -H 'X-Bintray-Debian-Component: main' -H 'X-Bintray-Debian-Architecture: amd64' -H 'X-Bintray-Publish: 1'
